# Generated by Django 5.1.1 on 2024-12-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productf',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
